### PR TITLE
Update nginx.conf with missing changes

### PR DESCRIPTION
**Pull request by ihor-sviziev**
**Fixed issues:**
1. `.user.ini` file should not be downloadable
2. `health_check.php` file should be executable, not downloadable. Needed for varnish configurations

Port changes:
- https://github.com/magento/magento2/commit/d764998480c7853c13c88d26a4530083cbd8a0a8#diff-25ad3490dcf1ce00f6aa9900b254ca91
- https://github.com/magento/magento2/commit/e5603018be8113f3acd124b896da4666c538dcea#diff-25ad3490dcf1ce00f6aa9900b254ca91

And others from current version of https://github.com/magento/magento2/blob/2.3-develop/nginx.conf.sample

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
Hi @danielozano,
Could you review my PR?

**Comment by danielozano** [comment]
Hi @ihor-sviziev I've been away from the pc for a few weeks, I will review it as soon as possible!

**Comment by danielozano** [comment]
Hi @ihor-sviziev I've trying to test the new configuration, have you tested it with versions previous to 2.3? When I try to run the setup I get a few 403 with the new config, so if it includes bc breaks we'll have to re-think the way we are including the default configuration in order to offer availability for older magento versions.

Maybe do you have any idea, any help is welcome! Also im going to ping @jalogut  to see his thougths.

**Comment by ihor-sviziev** [comment]
Hi @danielozano,
I just double checked on Magento 2.3.2 - everything works fine for me.
Also there was conflict with master branch - I fixed it.

**Comment by ihor-sviziev** [comment]
Hi @danielozano,
I was able to reproduce the issue you mentioned.  I reverted change on one line and it fixed.

Please check again

**Comment by danielozano** [comment]
Sure I'm going to test it and let you know the results! Thanks for your contribution!

**Comment by danielozano** [comment]
@ihor-sviziev I don't see any issues. I'm merging it! Thanks a lot for your work! I try to update the docs this week and create some release notes! I'll also take a look at your dockerfiles contribution! I know it's not the right place but if you've any advice about how keep the images updated let me know! Actually there is a PR to always use the latest tag, but I don't know if it's the rigth solution!

I'm closing the PR feel free to write us with your thoughts! (an issue or email what you prefer!)

**Comment by ihor-sviziev** [comment]
I think always using “latest” version is good enough solution.

**Pull request merged**
