### PR TITLE
Add support for different composer directory

### PR DESCRIPTION
**Pull request by ihor-sviziev**
**Pre-conditions**
 - real Magento installed in magento2/ directory of the project root.

Run `dockergento setup` in the project root.
When it it asking for magento directory and composer directory - type "magento2/".

After installation - try to run `dockergento composer install`. Now it fails, because composer runs in project root, not in root/magento2/.

This PR fixes this issue

### CODE REVIEW

**Comment by jalogut** [comment]
Hi @ihor-sviziev 

Thanks for your PR. I know about that. I did not add that code because composer already comes with and option `-d` for that. So you can ran composer like that:

```
dockergento composer install -d <composer_dir>
```

Would that be enough for you?

In fact, that is done automatically when executing `create-project` command:

- https://github.com/ModestCoders/magento2-dockergento/blob/master/console/commands/create-project.sh#L71

I also find a good idea to add that by default if not specified but we would need to check if the user executed composer with the option `-d` already. I mean, your PR will break for users executing `install -d <composer_dir>`. We need a solution that also works on such cases. What do you think?

**Comment by jalogut** [comment]
Hi @ihor-sviziev 

> I don't think so, we already have $COMPOSER_DIR env variable, so it would be better to use it instead of passing -d parameter to composer in console all the time

Sure, I agree with that but we need to prevent issues if someone tries to use `-d` parameter. An error message if someone executes a composer command with `-d` should be enough. Something like:

```
if [[ $@ == *" -d "*]]; then
    printf "${COLOR_RED}-d option cannot be used. Composer directory is automatically set to: ${COLOR_RESET}\n"
    echo ""
    echo "    COMPOSER_DIR=${COMPOSER_DIR}"
    echo ""
    exit 1
fi
```

It would be great if you could update the PR with something similar to this example. Thanks

**Comment by ihor-sviziev** [comment]
@jalogut,

I just updated my PR by adding support of `-d` parameter. It will work with and without passind `-d` or `--working-dir` parameter.

Just after updating found your comment. Should I update my solution?

**Comment by jalogut** [comment]
No, your PR is actually better than my suggestion. What I am not sure here is if we also have to check for `-d=` and `—working-dir=`. Do not know if that is also possible to use? In that case we should replace the `for` loop with 4 ifs like that:

```
If [[ $@ == *” -d ”*  || $@ == *” -d=”* ]] \
    || [[ $@ == *” —working-dir ”*  || $@ == *” —working-dir=”* ]]; then
#...
```

**Comment by ihor-sviziev** [comment]
@jalogut  I updated my code

**Comment by jalogut** [comment]
Hi @ihor-sviziev 

I merged your PR but had to set revert it because it is not working with the default settings:

~~~bash
  [Symfony\Component\Console\Exception\CommandNotFoundException]
  Command "." is not defined.
~~~

screenshot 2018-11-01 at 13 40 06

Could you check that and create a new PR? Thanks in advance

**Comment by ihor-sviziev** [comment]
Hi @jalogut,
I checked following cases:
1. `composer -d=./magento2 install` and `composer install -d=./magento2`- doesn't work
image
2. `composer install -d ./magento2` - works good, while `composer -d ./magento2 install` - doesnt:
image
3. `composer --working-dir=./magento2 install` works good, `composer install --working-dir=./magento2` - works good
image
4. `composer install --working-dir ./magento2` - works, `composer --working-dir ./magento2 install` - doesn't work
image


So according to this test looks like the only one correct fix - use `--working-dir=` parameter as a prefix for commands.


Will create new PR with this fix.

**Pull request merged**
